<template>
    <div class="navbar">
        <ul class="navbar-list">
            <li class="navbar-item"><a href="#">Home</a></li>
            <li class="navbar-item"><a href="#">About</a></li>
            <li class="navbar-item"><a href="#">Services</a></li>
        </ul>
    </div>
</template>

<style>
ul {
    list-style-type: none;
    margin: 5;
    padding: 5;
}

li {
    display: inline
}
</style>